language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install matplotlib
  - pip install python-igraph
  - pip install .
  - pip install python-coveralls
# command to run tests
script:
  - bash ./scripts/gen_baseline_images.sh && bash ./scripts/pytest_all.sh
after_success:
  - coveralls
