---
name: scedar_ci
on: 
  push: 
jobs:
  biopypir_testing:
    runs-on: ${{ matrix.os }} # ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6] 
        os: [ubuntu-latest] 
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2     
    #===============================================#
    - name: Set Up ${{matrix.os}}-py${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}   
    #===============================================#
    - name: Install Dependencies
      run: |
          pip install --upgrade pip setuptools wheel
          pip install .
          pip install python-coveralls
          pip install coverage
          pip install pytest-cov
          pip install pytest-mpl
          pip install nmslib
    #"pip install --no-binary :all: nmslib"
    #===============================================#
    - run: pwd
    - name: Run Tests
      run: |
        pytest --mpl-generate-path=tests/baseline_images \
          --color=yes --cov-config .coveragerc --maxfail=5  \
          --cov-branch --cov=scedar \
          --ignore=tests/test_cluster/test_mirac_large_data.py \
          tests
        
      
      #./scripts/gen_baseline_images.sh #&& ./scripts/pytest_all.sh
    - run: pwd
   #===============================================#
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    #===============================================#

